---
- name: Create persistent directories for MRTG Components
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'
  loop:
    - "{{ mrtg_data }}/logs"
    - "{{ mrtg_config }}/work"
    - "{{ mrtg_config }}/config"
